python -> python3
textmate/javascript.tmbundle pull request #67
Opened 2022-04-02 00:47 UTC by JackSteele

macOS 12 no longer includes python2, resulting in:

    $ /usr/bin/env python
    env: python: No such file or directory

2022-04-02 12:37 UTC, ogallagher approved these changes

2022-04-09 02:24 UTC, ogallagher commented
See [pr 1](https://github.com/JackSteele/javascript.tmbundle/pull/1) for `print` method syntax.

2022-04-09 02:25 UTC, ogallagher requested changes
See [pr 1](https://github.com/JackSteele/javascript.tmbundle/pull/1) for `print` method syntax.

2022-04-09 06:07 UTC, JackSteele commented
> See [pr 1](https://github.com/JackSteele/javascript.tmbundle/pull/1) for `print` method syntax.

Good catch, thanks!

2022-04-09 11:19 UTC, ogallagher approved these changes

2022-05-20 22:36 UTC, infininight commented
Pulled as b45aa5dce7edbe28f953d4497b8cd90788e6c29e and updated the underlying libary, thanks!

2022-05-20 22:36 UTC, closed without merging